// Generated by Wrangler on Wed Aug 07 2024 20:11:38 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	BACKMESH_KV: KVNamespace;
	BACKMESH_FIREBASE_KEY: string;
	PASSWORD: string;
}
