// Generated by Wrangler on Fri Aug 16 2024 15:40:53 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	BACKMESH_KV: KVNamespace;
	BACKMESH_FIREBASE_KEY: string;
	PASSWORD: string;
	TEST_USER_PASS: string;
	NIMBUS_GEMINI_API_KEY: string;
}
