name: Cloudflare Worker Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install wrangler
        run: npm install

      - name: Setup environment variables
        run: |
          echo "TEST_USER_PASS=${{ secrets.TEST_USER_PASS }}" >> .dev.vars
          echo "NIMBUS_GEMINI_API_KEY=${{ secrets.NIMBUS_GEMINI_API_KEY }}" >> .dev.vars

      - name: Run Cloudflare Worker test
        run: npx vitest run